/**
 * runtime.js
 * AMD 방식으로 로딩할때 SRT-1.0.js를 먼저 로딩 및 SRT의 ref를 제공한다. )
 */
define( [ 'srt' ], function () {
	return {
		navigator: window.navigator,
        Acceleration: window.Acceleration,
        Rotation: window.Rotation,
        CalendarEvent: window.CalendarEvent,
        CalendarRepeatRule: window.CalendarRepeatRule,
        CalendarEventFilter: window.CalendarEventFilter,
        CalendarFindOptions: window.CalendarFindOptions,
        CalendarError: window.CalendarError,
        Camera: window.Camera,
        CameraPopoverOptions : window.CameraPopoverOptions,
        CaptureError: window.CaptureError,
        CaptureAudioOptions: window.CaptureAudioOptions,
        CaptureImageOptions: window.CaptureImageOptions,
        CaptureVideoOptions: window.CaptureVideoOptions,
        CompassHeading: window.CompassHeading,
        CompassError: window.CompassError,
        ConfigurationData: window.ConfigurationData,
        Contact: window.Contact,
        ContactAddress: window.ContactAddress,
        ContactError: window.ContactError,
        ContactField: window.ContactField,
        ContactFindOptions: window.ContactFindOptions,
        ContactName: window.ContactName,
        ContactOrganization: window.ContactOrganization,
        Coordinates: window.Coordinates,
        DirectoryEntry: window.DirectoryEntry,
        DirectoryReader: window.DirectoryReader,
        DeviceSensor: window.DeviceSensor,
        Entry: window.Entry,
        File: window.File,
        FileEntry: window.FileEntry,
        FileError: window.FileError,
        FileReader: window.FileReader,
        FileSystem: window.FileSystem,
        FileTransfer: window.FileTransfer,
        FileTransferError: window.FileTransferError,
        FileUploadOptions: window.FileUploadOptions,
        FileUploadResult: window.FileUploadResult,
        FileWriter: window.FileWriter,
        Flags: window.Flags,
        LocalFileSystem: window.LocalFileSystem,
        Media: window.Media,
        MediaError: window.MediaError,
        MediaFile: window.MediaFile,
        MediaFileData: window.MediaFileData,
        Metadata: window.Metadata,
        Messaging: window.Messaging,
        Message: window.Message,
        MessagingError: window.MessagingError,
        Position: window.Position,
        PositionError: window.PositionError,
        ProgressEvent: window.ProgressEvent,
        requestFileSystem: window.requestFileSystem,
        resolveLocalFileSystemURI: window.resolveLocalFileSystemURI
	};
} );