
/**
 * 상수 정의
 */

exports.session = {
	secret: 'pollme2',
	key: 'pollme.sid',
};

const ANSI_PREFIX = '\u001b[', ANSI_SUFFIX = 'm';

exports.color = {
	RESET: ANSI_PREFIX + '0' + ANSI_SUFFIX,
	BRIGHT: ANSI_PREFIX + '1' + ANSI_SUFFIX
};

exports.foregroundColor = {
	BLACK: ANSI_PREFIX + '30' + ANSI_SUFFIX,
	RED: ANSI_PREFIX + '31' + ANSI_SUFFIX,
	GREEN: ANSI_PREFIX + '32' + ANSI_SUFFIX,
	YELLOW: ANSI_PREFIX + '33' + ANSI_SUFFIX,
	BLUE: ANSI_PREFIX + '34' + ANSI_SUFFIX,
	PURPLE: ANSI_PREFIX + '35' + ANSI_SUFFIX,
	CYAN: ANSI_PREFIX + '36' + ANSI_SUFFIX,
	WHITE: ANSI_PREFIX + '37' + ANSI_SUFFIX
};

exports.backgroundColor = {
	BLACK: ANSI_PREFIX + '40' + ANSI_SUFFIX,
	RED: ANSI_PREFIX + '41' + ANSI_SUFFIX,
	GREEN: ANSI_PREFIX + '42' + ANSI_SUFFIX,
	YELLOW: ANSI_PREFIX + '43' + ANSI_SUFFIX,
	BLUE: ANSI_PREFIX + '44' + ANSI_SUFFIX,
	PURPLE: ANSI_PREFIX + '45' + ANSI_SUFFIX,
	CYAN: ANSI_PREFIX + '46' + ANSI_SUFFIX,
	WHITE: ANSI_PREFIX + '47' + ANSI_SUFFIX
};
